[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = '''
    default-src 'self' blob: data: https:;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
    style-src 'self' 'unsafe-inline' https:;
    img-src 'self' data: blob: https:;
    font-src 'self' https: data:;
    connect-src 'self' https: wss:;
    frame-src 'self' https:;
    object-src 'none';
    base-uri 'self';
    form-action 'self';
  '''

# netlify.toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
